name: Build, Test & Generate Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build-test-generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.303

      - name: Setup Doxygen
        run: sudo apt-get install -y doxygen

      - name: Installing dependencies...
        run: dotnet restore

      - name: Building...
        run: dotnet build

      - name: Running test...
        run: dotnet test

      - name: Generating docs...
        working-directory: docs
        run: doxygen Doxyfile
        continue-on-error: false
